package assignmentJava.gui;

/**
 * An enumeration of all the panels inside the main window
 */
public enum panelList {
    ADD_MANUFACTURER,
    VIEW_DELETE_MANUFACTURER,
    SET_PRODUCT_MANUFACTURER,
    VIEW_PRODUCTS_MANUFACTURER,

    ADD_DELIVERY_AGENT,
    VIEW_DELETE_DELIVERY_AGENTS,

    ADD_SHOP,
    VIEW_DELETE_SHOP,
    ADD_INVENTORY_SHOP,
    VIEW_INVENTORY_SHOP,

    ADD_CUSTOMER,
    VIEW_DELETE_CUSTOMERS,
    VIEW_PURCHASES,

    PLACE_ORDER,
    VIEW_DELETE_PROCESS_UNPROCESSED_ORDERS,
    VIEW_PROCESSED_FAILED_ORDERS,

    ADD_PRODUCT,
    VIEW_DELETE_PRODUCTS
}
